name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Chọn service để build'
        required: true
        type: choice
        options:
          - backend
          - frontend

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image for ${{ inputs.service }}"
          docker build -t cryptosentiment/${{ inputs.service }}:latest ./${{ inputs.service }}

      - name: List Docker images
        run: docker images | grep cryptosentiment
